sudo: required
services:
  - docker

before_install:
  - docker build -t lym953/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lym953/multi-docker npm test

after_success:
  - docker build -t yimingl1/multi-client ./client
  - docker build -t yimingl1/multi-nginx ./nginx
  - docker build -t yimingl1/multi-server ./server
  - docker build -t yimingl1/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKEr_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.
  - docker push yimingl1/multi-client
  - docker push yimingl1/multi-nginx
  - docker push yimingl1/multi-server
  - docker push yimingl1/multi-worker
